# Generated by Django 5.2.6 on 2025-09-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_ordered_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
