# Generated by Django 5.2.6 on 2025-09-05 20:18

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role_vendorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
