# Generated by Django 5.2.6 on 2025-09-05 20:18

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_vendorprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='country',
            field=django_countries.fields.CountryField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
