# Generated by Django 5.2.6 on 2025-09-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_vendorprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
