# Generated by Django 5.2.4 on 2025-09-06 01:00

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customerprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='country',
            field=django_countries.fields.CountryField(max_length=200),
        ),
    ]
