# Generated by Django 5.2.6 on 2025-09-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_verified_alter_customuser_is_active_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='user',
            new_name='email',
        ),
    ]
