# Generated by Django 5.2.6 on 2025-09-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_otp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
