# Generated by Django 5.2.6 on 2025-09-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='email',
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
