# Generated by Django 5.2.6 on 2025-09-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payments_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='reference',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
