# Generated by Django 5.2.6 on 2025-09-16 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_quatity_orderitems_quantity'),
        ('payments', '0003_alter_payments_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='email',
        ),
        migrations.AddField(
            model_name='payments',
            name='orders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.orders'),
            preserve_default=False,
        ),
    ]
