# Generated by Django 5.2.6 on 2025-09-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreview',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
