# Generated by Django 5.2.6 on 2025-09-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
